title: Nordan 2025
email: bsm@hi.is
preposition: at
description: >-
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nordan-conference.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
karmdown:
  math_engine: mathjax
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
# who needs them


conference:

  # Language
  lang: en

  # Timezone
  tz: "+00:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
#      name: Nordan
      #img: 'compass-icon.svg' # inside /assets/images/
      url: 'https://nordan-conference.github.io/'
    breakpoint: md
    links:
      - name: Booklets and Program
        relative_url: /program/
      - name: Location
        relative_url: /location/
      - name: KAUS
        relative_url: /kaus/
      - name: Registration
        relative_url: /registration/
      - name: Previous Editions of Nordan
        menu:
          - name: (current)
            disabled: true
          - name: 2025
            relative_url: /2025/
          - name: 2024
            relative_url: /2024/
          - name: 2023
            relative_url: /2023/
          - name: 1997-2019
            relative_url: /1997-2019/


  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'full-logo.svg'
    links:
      #- name: Program
      #  relative_url: /program/
      #- name: How to get there
      #  relative_url: /location/
      #- name: Tickets
      #  disabled: true
      #  absolute_url: ''

  # Information boxes
  info_bars:
    #- title: Welcome to the Conference Theme for Jekyll!
    #  color: primary
    #  main_only: true
    #  text: |
    #    The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

    #    ---

    #    See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
    #- text: This is just some random content for demonstration purposes.
    #  color: warning
    #  pages_only: true

  # Live indications
  live:
    date: 011.09.2024
    timezone: GMT+0
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      #- name: Cat A
      #  color: info
      - name: Main
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map: false
      ## Initial map center point
      #home_coord: 47.37808, 8.53935
      ## Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      ## The following do match the Bootstrap design not too badly:
      ##   - Thunderforest.Neighbourhood
      ##   - Esri.WorldTopoMap
      #map_provider: "OpenStreetMap.Mapnik"
      #default_zoom: 17


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true

  kaus:
    logo:
      img: 'kaus.svg'
    url: /kaus
    title: KAUS 2025
    navigation:
      links:
        - name: Program
          relative_url: /kaus/program/
          activatable: true
        - name: Participants
          relative_url: /kaus/participants/
          activatable: true
        - name: Location
          relative_url: /kaus/location/
          activatable: true
        - name: NORDAN
          relative_url: /
          activatable: false
        - name: Previous Editions of KAUS
          relative_url: /kaus/previous-editions/
          activatable: true


